# -*- coding: utf-8 -*-
"""preprocessing_ClkBiasPINN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tB9Mim8f_UcWiMiA64_H5x3fjOee38_K
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **load the compressesed csv files**"""

import pandas as pd
rinex_path = '/content/drive/MyDrive/CLOCKBIASPINN/rinex_interpolated.gz'
rinex_cb = pd.read_csv(rinex_path, compression='gzip')
# For rinex_cb: Convert to 'G01', 'G02', ..., 'G32'
rinex_cb['sv_id'] = rinex_cb['sv_id'].astype(int).apply(lambda x: f'G{x:02d}')
rinex_cb.head()

igs_path = '/content/drive/MyDrive/CLOCKBIASPINN/combined_igs_clock.gz'
igs_cb = pd.read_csv(igs_path, compression='gzip')
igs_cb = igs_cb.drop(columns=['type', 'drift_s_per_s', 'drift_rate_s_per_s2'])
igs_cb = igs_cb[
        igs_cb['id'].apply(
            lambda x: isinstance(x, str) and x.startswith('G') and len(x) == 3 and x[1:].isdigit() and 1 <= int(x[1:]) <= 32
        )
    ].copy()
igs_cb = igs_cb.sort_values(by=['id', 'timestamp'])

igs_cb_temp = igs_cb.copy()
rinex_cb_temp = rinex_cb.copy()

# rename 'sv_id' in rinex_cb to 'id' for merging
rinex_cb_temp = rinex_cb_temp.rename(columns={'sv_id': 'id'})
rinex_cb_temp = rinex_cb_temp.rename(columns={'datetime_utc': 'timestamp'})
# Merge the two dataframes based on the common 'id' and 'timestamp' columns
# Using an inner merge to keep only rows where both dataframes have matching 'id' and 'timestamp'
merged_df = pd.merge(rinex_cb_temp, igs_cb_temp, on=['id', 'timestamp'], how='inner')

# Display the first few rows of the merged dataframe to verify
print(merged_df.head())
merged_df.columns

# save to csv and compress
merged_df.to_csv('/content/drive/MyDrive/CLOCKBIASPINN/merged_rinex_igs.gz', index=False, compression='gzip')

print("Merged dataframe saved to '/content/drive/MyDrive/CLOCKBIASPINN/merged_rinex_igs.gz'")

clkbias_G01 = merged_df[merged_df['id'] == 'G01'].copy()
clkbias_G01['bias_diff'] = clkbias_G01['bias_s'] - clkbias_G01['bias_interp_s']
# 1 second = 1,000,000,000 nanoseconds
ns_conversion_factor = 1e9

clkbias_G01['bias_interp_ns'] = clkbias_G01['bias_interp_s'] * ns_conversion_factor
clkbias_G01['bias_ns'] = clkbias_G01['bias_s'] * ns_conversion_factor
clkbias_G01['bias_diff_ns'] = clkbias_G01['bias_diff'] * ns_conversion_factor

clkbias_G01

