# -*- coding: utf-8 -*-
"""rinex_interpol_30s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrC1UfQyqGvsfj0j1BRFNia9kSpO2PIu
"""

!pip install gnss_lib_py

import pandas as pd

# 1. Load without parsing dates
csv_path = "combined_rinex_nav.csv"
df = pd.read_csv(csv_path)

# 2. Inspect what columns you’ve got
print("Columns in CSV:", df.columns.tolist())

# ——————————————————————————————
# 3. Reconstruct a datetime column
# If you see columns named 'gps_millis' and 'leap_seconds', you can do:
if {'gps_millis','leap_seconds'}.issubset(df.columns):
    GPSEPOCH = pd.Timestamp("1980-01-06T00:00:00")
    df['datetime_utc'] = (
        GPSEPOCH
        + pd.to_timedelta(df['gps_millis'], unit='ms')
        - pd.to_timedelta(df['leap_seconds'], unit='s')
    )
    print(df[['gps_millis','leap_seconds','datetime_utc']].head())

# Otherwise, if there’s a single numeric 'time' column that already represents seconds
# since GPS epoch, you could do:
elif 'time' in df.columns:
    GPSEPOCH = pd.Timestamp("1980-01-06T00:00:00")
    df['datetime_utc'] = GPSEPOCH + pd.to_timedelta(df['time'], unit='s')
    print(df[['time','datetime_utc']].head())

else:
    raise ValueError("No recognizable timestamp columns found in the CSV.")

# 4. Now you can sort by this new column
df.sort_values('datetime_utc', inplace=True)

# 5. (Optional) Save back out
df.to_csv(csv_path.replace(".csv","_with_datetime.csv"), index=False)
print("Saved with new datetime column.")

# Remove 'source' and 'source_file' columns if they exist
columns_to_drop = ['source', 'source_file']
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

print("\nColumns after dropping 'source' and 'source_file':", df.columns.tolist())

# Create a new DataFrame with the specified columns
rinex_df = df[['sv_id', 'SVclockBias', 'SVclockDrift', 'SVclockDriftRate', 'health', 'gnss_sv_id', 'gnss_id', 'datetime_utc']].copy()

# Display the head of the new DataFrame
print("\nHead of the new rinex_df:")
print(rinex_df.head())

import numpy as np
import pandas as pd
import os

# --- 1) Load your parsed navigation DataFrame ---
nav = rinex_df.copy()
nav['datetime_utc'] = pd.to_datetime(nav['datetime_utc'])

# --- 2) Interpolation parameters ---
dt      = 30.0            # seconds between points
horizon = 2 * 3600.0      # 2 h forecast window
n_steps = int(horizon / dt) + 1

# --- 3) Build every‐2 h anchors for each day in your data ---
days = nav['datetime_utc'].dt.floor('D').unique()
anchors = sorted(
    pd.Timestamp(day) + pd.Timedelta(hours=h)
    for day in days
    for h in range(0, 24, 2)
)

# --- 4) Loop over satellites and anchors, compute bias at each anchor ---
rows = []
for sv in nav['sv_id'].unique():
    sv_nav = nav[nav['sv_id'] == sv].sort_values('datetime_utc')
    for anchor in anchors:
        recs = sv_nav[sv_nav['datetime_utc'] <= anchor]
        if recs.empty:
            continue

        last = recs.iloc[-1]
        t0 = last['datetime_utc']
        a0 = last['SVclockBias']
        a1 = last['SVclockDrift']
        a2 = last['SVclockDriftRate']

        Δt = (anchor - t0).total_seconds()
        bias_interp = a0 + a1*Δt + a2*(Δt**2)

        rows.append({
            'sv_id':            sv,
            'broadcast_time':   t0,
            'broadcast_bias_s': a0,
            'anchor_time':      anchor,
            'bias_interp_s':    bias_interp
        })

# --- 5) Assemble into a single DataFrame and sort by the anchor datetime ---
df_out = pd.DataFrame(rows)
df_out.sort_values('anchor_time', inplace=True)
df_out.reset_index(drop=True, inplace=True)
df_out.sort_values(by=['broadcast_time', 'sv_id'], inplace=True)

import pandas as pd
import numpy as np
import os

# 1) Load your parsed RINEX DataFrame (already in memory)
#    Must have columns: ['sv_id','datetime_utc','SVclockBias','SVclockDrift','SVclockDriftRate']
nav = rinex_df.copy()
nav['datetime_utc'] = pd.to_datetime(nav['datetime_utc'])

# 2) Build the full list of 2 h anchors from midnight of first day
#    through midnight of the day after your last record
day0 = nav['datetime_utc'].dt.normalize().min()
dayN = nav['datetime_utc'].dt.normalize().max() + pd.Timedelta(days=1)
anchors = pd.date_range(day0, dayN, freq='2H')

# 3) For each (sv_id, anchor), pick the last broadcast ≤ that anchor
anchor_rows = []
for sv, grp in nav.groupby('sv_id'):
    grp = grp.sort_values('datetime_utc')
    for anchor in anchors:
        recs = grp[grp['datetime_utc'] <= anchor]
        if recs.empty:
            continue
        last = recs.iloc[-1]
        anchor_rows.append({
            'sv_id':             sv,
            'anchor_time':       anchor,
            'broadcast_time':    last['datetime_utc'],
            'SVclockBias':       last['SVclockBias'],
            'SVclockDrift':      last['SVclockDrift'],
            'SVclockDriftRate':  last['SVclockDriftRate']
        })

anchor_df = pd.DataFrame(anchor_rows)

# 4) Compute the bias exactly at each anchor
anchor_df['dt_anchor'] = (
    anchor_df['anchor_time'] - anchor_df['broadcast_time']
).dt.total_seconds()
anchor_df['bias_anchor_s'] = (
      anchor_df['SVclockBias']
    + anchor_df['SVclockDrift']     * anchor_df['dt_anchor']
    + anchor_df['SVclockDriftRate'] * anchor_df['dt_anchor']**2
)

# 5) Now interpolate in 30 s steps BETWEEN consecutive anchors
rows = []
dt = 30  # seconds

for sv, grp in anchor_df.groupby('sv_id'):
    grp = grp.sort_values('anchor_time')
    for cur, nxt in zip(grp.itertuples(index=False), grp.iloc[1:].itertuples(index=False)):
        t0 = cur.anchor_time
        a0 = cur.bias_anchor_s
        a1 = cur.SVclockDrift
        a2 = cur.SVclockDriftRate

        # 30 s grid from this anchor up to (but not including) the next
        times  = pd.date_range(t0, nxt.anchor_time, freq=f"{dt}S", inclusive='left')
        Δt      = (times - t0).total_seconds()
        bias    = a0 + a1*Δt + a2*(Δt**2)

        tmp = pd.DataFrame({
            'sv_id':         sv,
            'datetime_utc':  times,
            'bias_interp_s': bias
        })
        rows.append(tmp)

# 6) Assemble, sort, reset index
df_full = pd.concat(rows, ignore_index=True)
df_full.sort_values(['sv_id','datetime_utc'], inplace=True)
df_full.reset_index(drop=True, inplace=True)

print("✅ Done. Sample:")
print(df_full.head())
print("\nLast few rows:")
print(df_full.tail())

# prompt: save df_full to csv

df_full.to_csv("df_full.csv", index=False)
print("df_full saved to df_full.csv")

from google.colab import files

# Replace with the path to your CSV in Colab’s filesystem
csv_path = 'df_full.csv'

# This will prompt a download of the file to your local machine
files.download(csv_path)